config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:index, :edit, :update]
    get 'users/account'
  devise_for :users
  devise_scope :user do
    get "users", to: redirect("/users/sign_up")
  end

    get 'rooms/search'
  resources :rooms, only: [ :index, :new, :show, :create, :destroy]

    post 'reservations/confirm'
    post 'reservations/back'
  resources :reservations, only: [:index, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tops
    root to: "tops#index"
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :room_image
  has_one_attached :user_image
  belongs_to :user
  has_many :reservations, dependent: :destroy, foreign_key: 'room_id'
  validates :room_name, presence: true, length: {maximum:30}
  validates :introduction, presence: true, length: {maximum:150}
  validates :price, presence: true, numericality: {only_integer: true}
  validates :address, presence: true
  validates :room_image, presence:true
  
  def self.search(area)
    Room.where(['address LIKE ?', "%#{area}%"])
  end

  def self.search(key)
    Room.where(['room_name LIKE ? OR address LIKE ? OR price LIKE ?', "%#{key}%", "%#{key}%", "%#{key}%"]) 
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :search]

  def index
    @rooms = Room.where(user_id: current_user.id).order(updated_at: 'DESC')
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:room_id, :room_name, :introduction, :price, :address, :room_image, :user_id))
    @room.user = current_user
    if @room.save
      redirect_to :rooms
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def search
    @area = params[:area]
    @key = params[:key]
    if @area != nil 
     @rooms = Room.search(params[:area])
    elsif @key != nil 
     @rooms = Room.search(params[:key])
    else
     @rooms = Room.all
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to :tops
  end

  private
  
  def room_params
   params.require(:room).permit(:room_id, :room_name, :introduction, :price, :address, :room_image, :user_id, :user_image)
  end
end

app/views/rooms/index.html.erb
<div class = "my_rooms_page">
  <h4 class = "my_rooms_title">登録済みルーム一覧</h4>
  <table class = "my_rooms_table">
    <thead class = "my_rooms_thead">
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>

    <tbody class = "my_rooms_tbody">
    <% @rooms.each do |room| %>
      <tr>
        <td>
        <%= image_tag room.room_image, class: "room_image" %>
        </td>
        <td><%= link_to room.room_name, room_path(room) %></td>
        <td><%= room.introduction %></td>
        <td>¥<%= room.price %></td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<div class = "room_register_page">
  <%= render "shared/error", obj: @room %>
  <p class = "room_register_menu"><%= link_to "基本情報", new_room_path, {class: "register_attend"} %></p>

  <div class = "room_register_container">
  <%= form_with model: @room do |f| %>
    <table class = "room_register_table">
      <tr>
        <th class = "room_register_title">ルーム情報登録</th>
      </tr>
      <tr>
        <th>
          <%= f.label :room_name, "ルーム名", class: "room_register_label" %><span class = "required">*必須</span>
        </th>
        <td>
          <%= f.text_field :room_name, placeholder: "ルーム名を入力", class: "room_register_field" %>
        </td>
      </tr>
      <tr>
        <th>
          <%= f.label :introduction, "ルーム紹介", class: "room_register_label" %><span class = "required">*必須</span>
        </th>
        <td>
          <%= f.text_area :introduction, placeholder: "ルーム説明を入力", class: "room_register_area" %>
        </td>
      </tr>
      <tr>
        <th>
          <%= f.label :price, "料金", class: "room_register_label" %><span class = "required">*必須</span>
        </th>
        <td>
          <%= f.text_field :price, placeholder: "一日あたりの料金を入力", class: "room_register_field" %>
        </td>
      </tr>
      <tr>
        <th>
          <%= f.label :address, "住所", class: "room_register_label" %><span class = "required">*必須</span>
        </th>
        <td>
          <%= f.text_field :address, placeholder: "住所を入力", class: "room_register_field" %>
        </td>
      </tr>
      <tr>
        <th>
          <%= f.label :room_image, "ルーム画像", class: "room_register_label" %><span class = "required">*必須</span>
        </th>
        <td><%= f.file_field :room_image, id: :room_room_image, class: "room_register_image" %></td>
      </tr>
      <tr>
        <th><%= f.submit "登録", class: "room_register_button" %></th>
      </tr>
    </table>
  <% end %>
  </div>
</div>

app/views/rooms/search.html.erb
<div class = "room_search_page">
  <h5 class = "search_count">検索結果：<%= @rooms.count %>件</h5>
  <table class = "room_search_table">
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>住所</th>
        <th>料金</th>
      </tr>
    </thead>

    <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= image_tag room.room_image, class: "room_image" %></td>
        <td><%= link_to room.room_name, room_path(room) %></td>
        <td><%= room.address %></td>
        <td>¥<%= room.price %></td>
      </tr>
    <% end %> 
    </tbody>
  </table>
</div>

app/views/rooms/show.html.erb
<%= render "shared/error", obj: @reservation %>
<div class = "rooms_detail_page">
  <div class = "rooms_detail_nav">
    <div>
      <a><%= image_tag @room.room_image, class: "rooms_detail_room_image" %></a>
    </div>
    <div class = "rooms_detail_info">
      <p>
      <% if current_user.user_image.attached? %>
      <%= image_tag current_user.user_image, class: "room_detail_user_image" %>
      <% else %>
      <%= image_tag 'https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg', class: "room_detail_user_image" %>
      <% end %>
      </p>
      <div class = "rooms_detail_list">
        <p class = "rooms_detail_room_name"><%= @room.room_name %></p>
        <p><%= @room.address %></p>
      </div>
    </div>
    <div>
      <p class = "room_detail_introduction"><%= @room.introduction %></p>
    </div>
  </div>
  <div class = "rooms_detail_nav">
    <%= form_with model: @reservation, method: :post, url: reservations_confirm_path, local: true do |f| %>
    <%= f.hidden_field :room_id, value: @room.id %>
      <table class = "rooms_detail_table">
        <tr>
          <td>¥<%= @room.price %>/ 日</td>
        </tr>
        <tr>
          <th><%= f.label :start_date, "開始日" %></th>
          <td><%= f.date_field :start_date, placeholder: "年/月/日" %></td>
        </tr>
        <tr>
          <th><%= f.label :end_date, "終了日" %></th>
          <td><%= f.date_field :end_date, placeholder: "年/月/日" %></td>
        </tr>
        <tr>
          <th><%= f.label :number_of_people, "人数" %></th>
          <td><%= f.text_field :number_of_people %>
        </tr>
        <tr>
          <td><%= f.submit "予約する", class: "rooms_detail_reservation_btn" %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>